from geonode.maps.utils import file_upload
import os


def run(cmd, stdout=None, stderr=None):
    """Run command with stdout and stderr optionally redirected

    The logfiles are only kept in case the command fails.
    """

    # Build command
    msg = 'Argument cmd must be a string. I got %s' % cmd
    assert isinstance(cmd, basestring), msg

    s = cmd
    if stdout is not None:
        msg = 'Argument stdout must be a string or None. I got %s' % stdout
        assert isinstance(stdout, basestring), msg
        s += ' > %s' % stdout

    if stderr is not None:
        msg = 'Argument stderr must be a string or None. I got %s' % stdout
        assert isinstance(stderr, basestring), msg
        s += ' 2> %s' % stderr

    # Run command
    err = os.system(s)

    if err != 0:
        msg = 'Command "%s" failed with errorcode %i. ' % (cmd, err)
        if stdout:
            msg += 'See logfile %s for stdout details' % stdout
        if stderr is not None:
            msg += 'See logfile %s for stderr details' % stderr
        raise Exception(msg)
    else:
        # Clean up
        os.remove(stdout)
        os.remove(stderr)


def save_to_geonode(filename, user=None, title='Risiko layer',
                    overwrite=False):
    """Save a single layer file to local Risiko GeoNode

    Input
        filename: Layer filename of type .tif, .asc, .shp #or (.gml)
        user: Django User object
        title: String describing the layer
        overwrite: Boolean variable controlling whether existing layers
                   can be overwritten by this operation. Default is False
    Output
        layer object
    """

    # Extract fully qualified basename and extension
    basename, extension = os.path.splitext(filename)

    if extension == '.asc':
        # We assume this is an AAIGrid ASCII file such as those generated by
        # ESRI and convert it to Geotiff before uploading.

        # Create temporary tif file for upload and check that the road is clear
        upload_filename = basename + '.tif'
        msg = ('You have asked to upload the ASCII file "%s" and to do so I '
               'must first convert it to the TIF format. However, there is '
               'already a file named "%s" so you have to remove that first '
               'and try again. Sorry about that.' % (filename,
                                                     upload_filename))
        assert not os.path.exists(upload_filename), msg

        # Convert ASCII file to GeoTIFF
        cmd = ('gdal_translate -ot Float64 -of GTiff -co "PROFILE=GEOTIFF" '
               '%s %s' % (filename, upload_filename))

        run(cmd,
            stdout='%s_asc2tif_conversion.stdout' % basename,
            stderr='%s_asc2tif_conversion.stderr' % basename)
    else:
        # The specified file is the one to upload
        upload_filename = filename

    # Upload
    layer = file_upload(upload_filename,
                        user=user,
                        title=title,
                        overwrite=overwrite)

    # Clean up
    if extension == '.asc':
        os.remove(upload_filename)
        os.remove(upload_filename + '.aux.xml')

    # Return layer object
    return layer
