#!/bin/bash

# If this file is modified, you need to run
# pip install -e riab
# in a working directory outside the riab tree

echo; echo ">>> Running pylint to check code quality. See pylint.output for details"
cd $RIAB_HOME/riab/;pylint --disable=C0103 risiko impact > pylint.output 2> pylint.err
echo; echo ">>> Reporting FIXME's and TODO's in source code"
cd $RIAB_HOME/riab/;grep -n -R --exclude *.pyc --exclude *.log --exclude *.log.* FIXME risiko impact
cd $RIAB_HOME/riab/;grep -n -R --exclude *.pyc --exclude *.log --exclude *.log.* TODO risiko impact
echo; echo ">>> Reporting PEP8 non compliances"
cd $RIAB_HOME/riab/;pep8 --repeat --ignore=E203 risiko impact
echo; echo  ">>> Total number of lines: "
echo -n "   In impact: "
find $RIAB_HOME/riab/impact -name '*.py' -print0 | xargs -0 cat | wc -l
echo -n "   In risiko: "
find $RIAB_HOME/riab/risiko -name '*.py' -print0 | xargs -0 cat | wc -l
