#! /bin/bash

echo "---------------------------------------------------------"
echo "Installing Risiko and all its dependencies"
echo "This will take a little while depending on"
echo "the internet speed."
echo
echo "In any case, now is great time to go get a cup of coffee!"
echo "---------------------------------------------------------"


sudo apt-get -y update

# It is better to install Oracle Java but that process is done manually so we go with openjdk.
sudo apt-get install -y --force-yes openjdk-6-jre-headless

echo ">>> Installing Ubuntu packages"
# Python development prerequisites
sudo apt-get install -y vim zip unzip subversion git-core binutils build-essential python-dev python-setuptools python-imaging python-reportlab gdal-bin libproj-dev libgeos-dev python-urlgrabber python-scipy python-nose pep8 python-virtualenv python-numpy python-scipy python-gdal python-pastescript postgresql-contrib libpq-dev

function checkup() {
  REPO="$1"
  WORKING_DIR="$2"
  if [ -d "${WORKING_DIR}" ];
  then
      echo "Updating ${WORKING_DIR} from upstream"
      (cd "${WORKING_DIR}" && git pull)
  else
      git clone "git@github.com:${REPO}" "${WORKING_DIR}" || git clone "https://github.com/${REPO}" "${WORKING_DIR}"
  fi
}

echo ">>> Cloning the repositories"
# Get riab source code
checkup ingenieroariel/geonode.git geonode
cd geonode;git checkout synth; cd ..
checkup AIFDR/riab.git riab




echo ">>> Creating the virtual environment"
if [ -d riab_env ]; then
    echo 'It already exists...'
else
    virtualenv riab_env
    echo 'export DJANGO_SETTINGS_MODULE=risiko.settings' >> riab_env/bin/activate
fi

if grep -q RIAB_HOME ~/.bash_aliases
then
    echo "You already have RIAB_HOME in your ~/.bash_aliases"
else
    echo "export RIAB_HOME=`pwd`" >> ~/.bash_aliases
    echo 'alias risiko-activate="source $RIAB_HOME/riab_env/bin/activate;echo Risk In a Box virtual environment activated. Available commands are:; echo;echo risiko-test risiko-start risiko-stop risiko-clean risiko-upload risiko-populate;echo"' >> ~/.bash_aliases
    echo "Adding RIAB_HOME, RIAB_DATA and risiko-<commands> to your ~/.bash_aliases"
fi

echo ">>> Activating virtual environment"
source ~/.bash_aliases
source riab_env/bin/activate

echo ">>> Downloading bundled pre-requisites"

# Determine data source
zone=$(cat /etc/timezone)
if [ "$zone" == "Asia/Jakarta" ]; then
    export RISIKO_DATASOURCE="http://203.77.224.75/store/risiko_support_data"
    echo "Using Indonesian mirror for bundled pre-requisites: $RISIKO_DATASOURCE"
else
    export RISIKO_DATASOURCE="https://s3.amazonaws.com/geonodeariel"
    echo "Using Amazon mirror for bundled pre-requisites: $RISIKO_DATASOURCE"
fi

# Install GeoNode and it's pre-requisites
mkdir temp
cd temp
wget -c "$RISIKO_DATASOURCE/tomcat.zip"
wget -c "$RISIKO_DATASOURCE/geoserver-geonode-dev.war"
wget -c "$RISIKO_DATASOURCE/geonetwork.war"
wget -c "$RISIKO_DATASOURCE/riab-libs.pybundle"
wget -c "$RISIKO_DATASOURCE/geonode-client.zip"
cd ..

echo ">>> Installing riab dependencies"
unzip temp/tomcat.zip
cp temp/geoserver-geonode-dev.war tomcat/webapps/
cp temp/geonetwork.war tomcat/webapps/
pip install temp/riab-libs.pybundle

# FIXME: Need to add these to the bundle
pip install django==1.3
pip install fabric
pip install psycopg2


echo ">>> Copying media files into geonode/maps static folder"
pushd .
mkdir -p geonode/src/GeoNodePy/geonode/maps/static
unzip temp/geonode-client.zip -d geonode/src/GeoNodePy/geonode/maps/static/geonode
popd

echo ">>> Installing GeoNode and Riab in dev mode"
pip install -e geonode/src/GeoNodePy
pip install -e riab

export RIAB_DATA=$RIAB_HOME/riab_data

echo ">>> Get bundled test and demo data"
if [ -d $RIAB_DATA ]; then
    echo 'Test data area $RIAB_DATA already exists.'
else
    mkdir $RIAB_DATA;
    cd $RIAB_DATA

    # FIXME: Do these two as a loop of data name
    export TESTDATA_NAME='risiko_test_data'
    if [ -d $TESTDATA_NAME ]; then
        echo "Test data $TESTDATA_NAME already exists, skipping data download."
    else
	export TESTDATA_BUNDLE="$TESTDATA_NAME.tgz"
	export TESTDATA_SOURCE="$RISIKO_DATASOURCE/$TESTDATA_BUNDLE"
	wget -c $TESTDATA_SOURCE
	tar xvfz $TESTDATA_BUNDLE
	/bin/rm $TESTDATA_BUNDLE
    fi

    export DEMODATA_NAME='risiko_demo_data'
    if [ -d $DEMODATA_NAME ]; then
        echo 'Demo data $DEMODATA_NAME already exists, skipping data download.'
    else
	export DEMODATA_BUNDLE="$DEMODATA_NAME.tgz"
	export DEMODATA_SOURCE="$RISIKO_DATASOURCE/$DEMODATA_BUNDLE"
	wget -c $DEMODATA_SOURCE
	tar xvfz $DEMODATA_BUNDLE
	/bin/rm $DEMODATA_BUNDLE
    fi

    cd ..
fi

mkdir -p logs


echo ""
echo "Congratulations, you have installed Risk in a Box"
echo
echo "We have added a shortcut called 'risiko-activate' to your ~/.bash_aliases file to activate Risk In a Box"
echo "~/.bash_aliases is sourced every time you open a new terminal. For now just do:"
echo
echo "source ~/.bash_aliases"
echo "risiko-activate"
echo
