#!/bin/bash

# If this file is modified, you need to run
# pip install -e riab
# in a working directory outside the riab tree

# Clean stale data in GeoServer, GeoNetwork and Django.
risiko clean

# Start GeoNode servers in silent mode
risiko start

# Show code quality
risiko-lint

# Give GeoServer time to boot
sleep 10

# Run unit tests
if [ $# -eq 0 ];then
    args="risiko impact --with-id"
else
    args=$@
fi

risiko test $args --noinput

# Stop GeoNode
risiko stop
