#! /bin/bash

echo "---------------------------------------------------------"
ecoh "Uninstalling Risiko                                      "
echo
echo "This will completely remove Risiko, its datasets,        "
echo "cached install files, the virtual (python) environment   "
echo "and .bash_aliases - although a copy will be left in      "
echo ".bash_aliases_copy                                       "
echo
echo "System wide Risiko dependencies will be left intact      "
echo
read -p "Do you wish to remove Risiko [Y/N](N) ?" answer
case $answer in
    y | Y | yes | YES | Yes) answer="y";;
    * ) echo "OK - nothing done"; exit 0;
esac

read -p "ARE YOU SURE [Y/N](N) ?" answer
case $answer in
    y | Y | yes | YES | Yes) answer="y";;
    * ) echo "OK - nothing done"; exit 0;
esac

risiko-clean
deactivate  # FIXME: This doesn't work
cd

echo "Removing /usr/share/risiko (cached install files)"
sudo /bin/rm -rf /usr/share/risiko

echo "Cleaning up in /tmp"
sudo /bin/rm -rf /tmp/distribute-0.6.*  # This is so annoying unless deleted

echo "Moving .bash_alias to .bash_aliases_copy"
mv ~/.bash_aliases ~/.bash_aliases_copy

echo "Removing Risiko"
/bin/rm -rf $RIAB_HOME

echo
echo "Success, You have removed Risk in a Box"
echo
echo "To reinstall "
echo "1) wget http://bit.ly/risiko-install"
echo "2) bash risiko-install"
echo
