#! /bin/bash

echo "---------------------------------------------------------"
echo "Installing Risiko and all its dependencies"
echo "This will take a little while depending on"
echo "the internet speed."
echo
echo "In any case, now is great time to go get a cup of coffee!"
echo "---------------------------------------------------------"


sudo apt-get -y update

# It is better to install Oracle Java but that process is done manually so we go with openjdk.
sudo apt-get install -y --force-yes openjdk-6-jre-headless

echo ">>> Installing Ubuntu packages"
# Python development prerequisites
sudo apt-get install -y vim zip unzip subversion git-core binutils build-essential python-dev python-setuptools python-imaging python-reportlab gdal-bin libproj-dev libgeos-dev python-urlgrabber python-scipy python-nose pep8 python-virtualenv python-numpy python-scipy python-gdal python-pastescript postgresql-contrib libpq-dev gettext python-psycopg2 ant

# Java development prerequisites, make sure to use this line with --no-install-recommends
# the ant package behaves badly and wants to install gcj.
sudo apt-get install -y --force-yes ant --no-install-recommends

echo ">>> Creating the virtual environment"
if [ -d riab_env ]; then
    echo 'It already exists...'
else
    virtualenv riab_env
    echo 'export DJANGO_SETTINGS_MODULE=risiko.settings' >> riab_env/bin/activate
fi

if grep -q RIAB_HOME ~/.bash_aliases
then
    echo "You already have RIAB_HOME in your ~/.bash_aliases"
else
    echo "export RIAB_HOME=`pwd`" >> ~/.bash_aliases
    echo 'alias risiko-activate="source $RIAB_HOME/riab_env/bin/activate;echo Risk In a Box virtual environment activated. Available commands are:; echo;echo risiko-test risiko-start risiko-stop risiko-clean risiko-upload risiko-populate;echo"' >> ~/.bash_aliases
    echo 'source $RIAB_HOME/riab/extras/django_bash_completion' >> ~/.bash_aliases
    echo "Adding RIAB_HOME, RIAB_DATA and risiko-<commands> to your ~/.bash_aliases"
fi



echo ">>> Downloading bundled pre-requisites"

# Determine data source
zone=$(cat /etc/timezone)
if [ "$zone" == "Asia/Jakarta" ]; then
    export RISIKO_DATASOURCE="http://203.77.224.75/store/risiko_support_data"
    echo "Using Indonesian mirror for bundled pre-requisites: $RISIKO_DATASOURCE"
else
    export RISIKO_DATASOURCE="https://s3.amazonaws.com/geonodeariel"
    echo "Using Amazon mirror for bundled pre-requisites: $RISIKO_DATASOURCE"
fi

# Install GeoNode and it's pre-requisites
mkdir -p temp
cd temp
wget -c "$RISIKO_DATASOURCE/tomcat.zip"
wget -c "$RISIKO_DATASOURCE/geoserver-geonode-dev.war"
wget -c "$RISIKO_DATASOURCE/geonetwork.war"
wget -c "$RISIKO_DATASOURCE/riab-libs.pybundle"
wget -c "$RISIKO_DATASOURCE/geonode-client.zip"
wget -c "$RISIKO_DATASOURCE/risiko_test_data.tgz"
wget -c "$RISIKO_DATASOURCE/risiko_demo_data.tgz"
cd ..


function checkup() {
  REPO="$1"
  WORKING_DIR="$2"
  if [ -d "${WORKING_DIR}" ];
  then
      echo "Updating ${WORKING_DIR} from upstream"
      (cd "${WORKING_DIR}" && git pull)
  else
      git clone "git@github.com:${REPO}" "${WORKING_DIR}" || git clone "https://github.com/${REPO}" "${WORKING_DIR}" || git clone "http://github.com/${REPO}" "${WORKING_DIR}"
  fi
}



echo ">>> Cloning the repositories"
# Get riab source code
checkup GFDRR/geonode.git geonode
checkup AIFDR/riab.git riab



echo ">>> Activating virtual environment"
source ~/.bash_aliases
source riab_env/bin/activate

echo ">>> Installing riab dependencies"
unzip -o temp/tomcat.zip
cp temp/geoserver-geonode-dev.war tomcat/webapps/
cp temp/geonetwork.war tomcat/webapps/
tar xvfz temp/risiko_test_data.tgz
#FIXME: We should remove this from the installer, it is too much data
# and more related to our demo server than riab development.
tar xvfz temp/risiko_demo_data.tgz
mkdir -p geonode/src/GeoNodePy/geonode/maps/static
unzip -o temp/geonode-client.zip -d geonode/src/GeoNodePy/geonode/maps/static/geonode
mkdir -p logs
pip install temp/riab-libs.pybundle

# FIXME: Need to add these to the bundle
pip install django==1.3

echo ">>> Installing GeoNode and Riab in dev mode"
pushd .
cd geonode/src
pip install -e GeoNodePy
popd
pip install -e riab

echo ">>> Building and installing the Calculator application"
pushd .
cd riab/calculator
ant init
ant dist
cp -Rf build/calculator/WEB-INF/app/static ../../geonode/src/GeoNodePy/geonode/maps/static/calculator

echo ""
echo "Congratulations, you have installed Risk in a Box"
echo
echo "We have added a shortcut called 'risiko-activate' to your ~/.bash_aliases file to activate Risk In a Box"
echo "~/.bash_aliases is sourced every time you open a new terminal. For now just do:"
echo
echo "1) source ~/.bash_aliases"
echo "2) risiko-activate"
echo
