#!/bin/bash
export NOSE_WITH_COVERAGE=True
echo; echo ">>> Cleaning up environment, deleting data from the development server"; echo
risiko-clean
echo; echo ">>> Starting tomcat server with GeoServer and GeoNetwork"; echo
$RIAB_HOME/tomcat/bin/catalina.sh start
echo; echo ">>> Starting Django server with GeoNode"; echo
paster serve --reload $RIAB_HOME/riab/extras/project.paste.ini &
echo; echo ">>> Running pylint to check code quality. See pylint.output for details"; echo
cd $RIAB_HOME/riab/;pylint risiko impact > pylint.output 2> pylint.err
echo; echo ">>> Reporting FIXME's in source code"; echo
cd $RIAB_HOME/riab/;grep -n -R --exclude *.pyc --exclude *.log --exclude *.log.* FIXME risiko impact
echo; echo ">>> Reporting PEP8 non compliances"; echo
cd $RIAB_HOME/riab/;pep8 --repeat --ignore=E203 risiko impact
echo; echo  ">>> Total number of lines: "
echo -n "   In impact: "
find $RIAB_HOME/riab/impact -name '*.py' -print0 | xargs -0 cat | wc -l
echo -n "   In risiko: "
find $RIAB_HOME/riab/risiko -name '*.py' -print0 | xargs -0 cat | wc -l
echo;echo ">>> Running unit tests";echo
cd $RIAB_HOME/riab/risiko; ./manage.py test risiko impact --verbosity=0
echo;echo ">>> Stopping all servers";echo
risiko-stop
