#!/usr/bin/env python
"""Upload test data to GeoServer

# Data is assumed to reside in subdirectories of ./data named by their workspace.
# The standard workspace names are
# - hazard
# - exposure
# - boundaries
# - impact
# - sources
"""

import sys
import os
import string

from impact.tests.utilities import DEMODATA
from risiko.utilities import save_to_geonode, RisikoException
from impact.auth import create_risiko_superuser

if __name__ == '__main__':
    print 'Uploading all files from %s to Risiko' % DEMODATA

    user = create_risiko_superuser()
    layers = save_to_geonode(DEMODATA, user=user, overwrite=True)#, verbose=True)
    print 'Layers uploaded:'
    for layer in layers:
        print '    %s' % layer
