#!/usr/bin/python
import os
import sys
import boto
from optparse import OptionParser

usage = 'Upload one file to the AIFDR amazon bucket. The usage is: %prog file_to_upload. It requires two enviroment variables: AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY'
parser = OptionParser(usage=usage)
options, args = parser.parse_args()

if len(args) != 1:
    raise Exception(usage)


AWS_ACCESS_KEY_ID = os.environ['AWS_ACCESS_KEY_ID']
AWS_SECRET_ACCESS_KEY = os.environ['AWS_SECRET_ACCESS_KEY']

bucket_name = 'aifdr'
conn = boto.connect_s3(AWS_ACCESS_KEY_ID,
                       AWS_SECRET_ACCESS_KEY)

#bucket = conn.create_bucket(bucket_name,
#        location=boto.s3.connection.Location.DEFAULT)
bucket = conn.get_bucket(bucket_name)
testfile = args[0]
print 'Uploading %s to Amazon S3 bucket %s' % (testfile, bucket_name)

def percent_cb(complete, total):
    sys.stdout.write('.')
    sys.stdout.flush()

from boto.s3.key import Key
k = Key(bucket)
k.key = args[0]
k.set_contents_from_filename(testfile,
                             cb=percent_cb,
                             num_cb=10)
